### ISSUE TITLE
Perspicacity and initial thanks

### ISSUE THREAD

**Issue by Hovelander** [joeferraro/react-native-cookies#1]
Thanks for getting the ball rolling on this little project!  I've been researching for a few days now on how to handle session authentication cookies for a react-native app and truly appreciate you initiating under a pragmatic and common sense name.

Newbs like me will no doubt stumble their way to your doorstep here while trying to grok this awesome new framework.

Molte grazie e buona fortuna!

**Comment by joeferraro** [comment]
you're welcome and thanks for the note :+1:
