### ISSUE TITLE
Change argument name to be descriptive of return value

### ISSUE THREAD

**Issue by ataber** [joeferraro/react-native-cookies#10]
[This line](https://github.com/joeferraro/react-native-cookies/blob/master/index.js#L29), as well as the documentation, seems to suggest that the `err` argument to the callback for `getAll` will be something like an error message, but [here](https://github.com/joeferraro/react-native-cookies/blob/master/RNCookieManagerIOS/RNCookieManagerIOS.m#L60) the argument is the list of cookies. Please change the naming so it's clearer how to get the cookies from the call. Thanks!

PS: If need be, I can make a PR, just say the words :)

**Comment by mouthzipper** [comment]
+1

**Comment by joeferraro** [comment]
will certainly accept the PR, cheers @ataber
