### ISSUE TITLE
AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

### ISSUE THREAD

**Issue by hedikasmanto** [joeferraro/react-native-cookies#100]
Hi, 
While upgrade to RN 0.56. I have found this error.. But on RN 0.55.4, this package working perfectly

:react-native-cookies:processReleaseManifest UP-TO-DATE
:react-native-cookies:processReleaseResources
/Users/XXXX/Workspace/app-react-native/node_modules/react-native-cookies/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/Users/XXXX/Workspace/app-react-native/node_modules/react-native-cookies/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/Users/XXXX/Workspace/app-react-native/node_modules/react-native-cookies/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15:21-54: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
    
/Users/XXXX/Workspace/app-react-native/node_modules/react-native-cookies/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:3: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.

/Users/XXXX/Workspace/app-react-native/node_modules/react-native-cookies/android/build/intermediates/res/merged/release/values-v24/values-v24.xml:4: error: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.

/Users/XXXX/Workspace/app-react-native/node_modules/react-native-cookies/android/build/intermediates/res/merged/release/values-v26/values-v26.xml:15: error: Error: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

**Comment by ptraeg** [comment]
I had this same issue as well and fixed in in PR #102

**Comment by alainib** [comment]
i still get the use

**Comment by hedikasmanto** [comment]
@alainib 
I had solved this problem.

Just add below line into your build.gradle in your android folder (TOP LEVEL)

subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion 26
                buildToolsVersion '26.0.3'
            }
        }
    }
}

You can change compileSdkVersion and buildToolsVersion variable, but I suggest to make them similar with android/app/build.gradle. So while you compile your react native project, all requested android modules will be recompiled based on your build.gradle setting

**Comment by zhangxy1219** [comment]
No hardcode version recommended.
`subprojects {
    afterEvaluate {project ->
        if (project.hasProperty("android")) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
            }
        }
    }
}`
