### ISSUE TITLE
Cannot read property 'getAll' of undefined

### ISSUE THREAD

**Issue by eyaleizenberg** [joeferraro/react-native-cookies#2]
Hi,
I am faced with the same issue as this: https://github.com/facebook/react-native/issues/1274

This is roughly my code:
var CookieManager = require('react-native-cookies');
    CookieManager.getAll((err, res) => {
      console.log('cookies!');
      console.log(err);
      console.log(res);
    });

The cookie manager is defined, and so is the getAll method.

Someone suggested that maybe the files where not properly added to the xcode project. Do I need to "add files to.." the most top level name of the app (the one that states the sdk under it) or to the folder which has the same app name?

Thanks!

**Comment by joeferraro** [comment]
@eyaleizenberg the folder which has the same app name. Ensure `Copy items if needed` and `Create groups` are checked.

**Comment by eyaleizenberg** [comment]
@joeferraro Cool that worked. You should really update the read me for this.

Thanks! :smile:

**Comment by joeferraro** [comment]
:+1:
