### ISSUE TITLE
how can i get the cookies header string?

### ISSUE THREAD

**Issue by rayshen** [joeferraro/react-native-cookies#21]
your framework is very good ,thanks
But I find that using function "CookieManager.get(url, (err, res) => { }"  i get the local cookie and it is in json format.
but i need the cookies header for another request ,it is like "aaa=xxxx;bbb=yyyy;ccc=zzzz",how can i get this ?

=======================
ok i know . i read your code (iOS) , i find i can use this function to get it ,and the string is in  header["Cookie"]

RCT_EXPORT_METHOD(getHeader:(NSURL *)url callback:(RCTResponseSenderBlock)callback) {
      NSArray *cookies = [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookiesForURL:url];
      NSDictionary *header = [NSHTTPCookie requestHeaderFieldsWithCookies:cookies];
      callback(@[[NSNull null], header]);
}

**Comment by tomzaku** [comment]
@rayshen Could you clarify the detail how can do that?

**Comment by tomzaku** [comment]
``` javascript
export const jsonToStringCookie = (cookieJson= {session: '"abc"'}) => {
  let cookieString= ''
  Object.keys(cookieJson).map((title, index) => {
    cookieString = cookieString + `${title} = ${cookieJson[title]};`
  })
  return cookieString;
}
```
I'm only thinking that way
