### ISSUE TITLE
no such package available : react-native-cookies

### ISSUE THREAD

**Issue by sesteva** [joeferraro/react-native-cookies#23]
It seems the package is no longer published in npm

"'react-native-cookies' is not in the npm registry"

**Comment by Psykar** [comment]
Definitely still exists:
https://www.npmjs.com/package/react-native-cookies
```
/tmp/cookies$ npm install react-native-cookies                                                                      
cookies@1.0.0 /tmp/cookies
`-- react-native-cookies@1.0.0  extraneous
```

**Comment by sesteva** [comment]
I swear earlier today was gone!
Sorry about that. 
Thanks for the response. By they way , it work beautifully thanks

**Comment by khulas18** [comment]
I am having the same issue. How do you solve this one?
