### ISSUE TITLE
Get/Delete a single cookie

### ISSUE THREAD

**Issue by eyaleizenberg** [joeferraro/react-native-cookies#3]
Hi,
Any chance add the ability to get/delete a single cookie? Right now it's either getAll or deleteAll.

Thanks a bunch!

**Comment by mouthzipper** [comment]
+1

**Comment by joeferraro** [comment]
https://github.com/joeferraro/react-native-cookies/pull/11

**Comment by brunck** [comment]
These changes don't allow for deleting a cookie by name.
