### ISSUE TITLE
RNPM link script is not working on 0.29 applications 

### ISSUE THREAD

**Issue by dphov** [joeferraro/react-native-cookies#39]
Reference #37 , we should update rnpm script so that the installation could be easier.
@joeferraro

**Comment by af7** [comment]
+!

**Comment by akzhou** [comment]
+1

**Comment by Luiz0tavio** [comment]
+1

**Comment by cbcye** [comment]
+1 , how to manual import. my RN is 0.31

**Comment by geniusgordon** [comment]
+1

**Comment by liquidprogrammer** [comment]
Hey there.
For manual importing u can add several lines in this files (on android):

## MainApplication.java
...
**import com.psykar.cookiemanager.CookieManagerPackage;**
...
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          ....,
          **new CookieManagerPackage()**
      );
    }

## android/app/build.gradle
dependencies {
    ...
    **compile project(':react-native-cookies')**
}

## android/settings.gradle
include ':app', ..., **':react-native-cookies'**
...
**project(':react-native-cookies').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-cookies/android')**

After that you should reinstall your app on device/emulator with **react-native run-android**.
And everything should work


_P.S. For ios, as i remember, you need to add react-native-cookies xcode project to libraries list of your xcode project. May be something else, but im not sure_

**Comment by adamkdean** [comment]
Not working on 0.31 😢

**Comment by joeferraro** [comment]
Cheers @liquidprogrammer
