### ISSUE TITLE
Upgrade buildToolsVersion to > 25.0.0

### ISSUE THREAD

**Issue by Brian-Kaplan** [joeferraro/react-native-cookies#54]
The minimum buildToolsVersion for android studio 2.3 is 25.0.0

I cannot use your project unless you update the buildToolsVersion.

**Comment by joeferraro** [comment]
This won't suffice? https://github.com/joeferraro/react-native-cookies/blob/8747babbf6e47a2a9351667138a791406e1667fc/android/build.gradle#L15

**Comment by Brian-Kaplan** [comment]
Wow totally missed this... guess I pulled the trigger on this issue a little too quickly. my bad. thanks for pointing this out.
