### ISSUE TITLE
 CookieManager.clearAll() expects 1 argument on ios

### ISSUE THREAD

**Issue by Ouadie** [joeferraro/react-native-cookies#68]
**Version:3.2.0** ` CookieManager.clearAll();` Works on **Android** but not on **iOS**

![simulator screen shot 9 aug 2017 12 54 52](https://user-images.githubusercontent.com/1163583/29118507-8249ef22-7d02-11e7-86d5-b5428058e0b9.png)

**Comment by joeferraro** [comment]
You'll need to unlink/relink this library as the method signatures have changed due to promises

**Comment by Ouadie** [comment]
it works now after unlinking it then linking it again. Thanks!

**Comment by joeferraro** [comment]
no worries, @Ouadie. cheers
