### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by isairz** [joeferraro/react-native-cookies#7]
I want to manage cookie in react native.
So I found this modules, but this is not working in android.

Would you mind to make another version that supports android platform?

Thanks.

**Comment by ryanmcdermott** [comment]
+1

**Comment by joeferraro** [comment]
i'd certainly accept a PR for this ... I'm pretty sure it's as simple as using `CookieManager`, but I don't have the time to implement/test at the moment.

```
CookieManager cookieManager = CookieManager.getInstance();
```

**Comment by ryanmcdermott** [comment]
As of RN 0.12, Android `<Webview>` is not available, as per this issue: https://github.com/facebook/react-native/issues/2701

After it's supported then adding an Android CookieManager will be really useful. I would love to try hacking on the implementation, but without Webview I wouldn't know where to begin testing!

**Comment by evanwalsh** [comment]
[As of 0.17.0](https://github.com/facebook/react-native/releases/tag/v0.17.0), React Native supports WebView on Android! :tada: :smile:

**Comment by 9mm** [comment]
So does this work for android now?

**Comment by Psykar** [comment]
Interestingly the Android API only allows you to get a cookie given a URL and only as the string that should be sent as the HTTP Request: http://developer.android.com/reference/android/webkit/CookieManager.html

I've started some work here https://github.com/psykar/react-native-cookies but it's *very* WIP'y at the moment.
Will likely mean adding a new top level API setFromHeader and getCookieHeader (or similar) which I'll implement on iOS as well, although open to suggestions on how to handle this better.

**Comment by bartonhammond** [comment]
@Psykar Any update on the Android API for CookieManager?

**Comment by Psykar** [comment]
@bartonhammond PR #11 is ready as far as I'm concerned, and has been working for me :)

**Comment by bartonhammond** [comment]
@Psykar Oh!  I didn't notice that!

**Comment by bartonhammond** [comment]
@Psykar Do you have a example project for Android? Or point me to one?
