### ISSUE TITLE
Getting an error on `CookieManager`’s `setFromResponse` function

### ISSUE THREAD

**Issue by oferRounds** [joeferraro/react-native-cookies#73]
Hi!

When trying to use the `CookieManager`’s `setFromResponse` function the iOS simulator, while passing the following values: `https://app.hibob.com`, `user_session=abcdefg; Max-Age=7200; Expires=Fri, 25 Aug 2017 09:34:22 GMT; Path=/; Domain=hibob.com; Secure; HTTPOnly` I get the error:

> JSON value <value> of type `NSString` can not be converted to `NSDictionary`

What am I doing wrong? I mean, I understand the error, but in the example it seems a string, which is also not convertible to JSON, is passed. I was looking for the API — along with the expected types — but was not able to find it.

I’d love for some help...

Thanks!

**Comment by oferRounds** [comment]
When debugging from the native side, I see that in fact the second param which is being passed to the `NSHTTPCookie`’s method `cookiesWithResponseHeaderFields:forURL:` is nil, as the conversion failed.

**Comment by oferRounds** [comment]
Tried to use also the equivalent `set` method, but getting an `undefined` in the result.

**Comment by oferRounds** [comment]
Oh, well I see now that the completion block, on the iOS native side, will always respond with a nil value. Why is that?

`RNCookieManagerIOS`, line 38: `resolve(nil);`

**Comment by oferRounds** [comment]
And one last question :)
It seems as if `RNCookieManagerIOS` expects the `expiration` date be in `IOS8601`, as when passing the date in a **UTC/GMT Format** it fails and says it expects the `IOS8601`. Why is that? If I understand right, the UTC/GMT Format is standard when it comes to `Set-cookie`.

**Comment by iegik** [comment]
Duplicate https://github.com/joeferraro/react-native-cookies/issues/15

**Comment by iegik** [comment]
> expects the expiration...
https://github.com/joeferraro/react-native-cookies/issues/36
