### ISSUE TITLE
Android: Syncing Cookies with Webview?

### ISSUE THREAD

**Issue by dahjelle** [joeferraro/react-native-cookies#79]
I have a React Native app with a `WebView`. I log in to the web view, and then was hoping I could see all the cookies that the `WebView` uses by something like:

```
CookieManager.get(BASE_URL).then(console.log.bind(console, 'cookies'));
```

But I'm only getting a **subset** of the cookies that I think must be in the `WebView`. (i.e. the web app requires 3 or 4 cookies for authentication, and has them when I look in a desktop browser)

I'm at a loss as to why this might be happening. Does the `WebView` and `cookieHandler` only sync periodically? Does Android only allow access to, say `httpOnly` cookies (though that doesn't appear to be what is happening here)? It should support sub-domains? (None of these appear to be the issue as far as I can tell…) Thoughts?

I added a `System.out.println` to `CookieManagerModule.java`, in the `get` method, and it appears that the Cookie information that is coming from React Native isn't complete, either.

---

I tried to add some logging to `ForwardingCookieHandler.java`, but I haven't had any luck getting them to appear. I'm guessing that React Native isn't getting recompiled for some reason…I'm happy to dig into this a bit if someone has a pointer or two. :-D I'm mostly a JS dev so it takes a bit more work to understand what Java is doing.

**Comment by dahjelle** [comment]
I have verified that the other cookies are in the `WebView` using Chrome's remote debugger.

**Comment by dahjelle** [comment]
To put some details on my previous comment, here's what Chrome's remote debugger shows me:

![untitled](https://user-images.githubusercontent.com/156557/32279211-0b7d1024-bee6-11e7-98d2-1288697d3c6b.png)

Whereas this code

```
CookieManager.get('https://david-rubix.iconcmo.com/').then(
  console.log.bind(console, 'cookies')
);
```

gives me

![untitled 2](https://user-images.githubusercontent.com/156557/32279324-6d582a9a-bee6-11e7-835a-c9ab2a5fcb01.png)

**Comment by dahjelle** [comment]
Hmm…I turned off the `SameSite` attribute server-side, and then I had access to all the cookies. This is apparently not an issue of either `react-native-cookies` or even `react-native`, but looks to be an issue of the Android WebView, at least according to [this StackOverflow post](https://stackoverflow.com/questions/40798777/android-extrac-samesite-strict-cookie-from-webview-or-url).

**Comment by joeferraro** [comment]
thanks for this analysis @dahjelle

**Comment by dahjelle** [comment]
You bet!

For whatever it is worth, I posted a couple bug reports about this issue:

- [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=780491&can=2&q=samesite&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified)
- [Android bug](https://issuetracker.google.com/issues/68756461)

Do you think, @joeferraro, it'd be worth adding a note to the docs about this issue?
